### ISSUE TITLE
Segfaults on animations

### ISSUE THREAD

**Issue by jbuchermn** [jbuchermn/pywm#10]
Getting segfaults here after 1-2 minutes of the program being open. A bit of a pattern I've noticed is that normally, an animation is played at some point between animation queues. Whenever there's a segfault, there are two animations queued with no animation played between. I uploaded this part of the log [here](https://pastebin.com/GEpxwKU2).

Mesa: 21.3.7-2 on Intel Tiger Lake (Xe) Graphics

__Originally posted by @carterisonline in https://github.com/jbuchermn/newm/issues/91#issuecomment-1084604996__

**Comment by jbuchermn** [comment]
@carterisonline can you reproduce these consistently? I.e. by opening certain windows, triggering a certain animation, ...

**Comment by carterisonline** [comment]
Seems to only happen when focusing a window, although still appears to be random. Previously open apps seem to crash less, though. Unable to reproduce this on a VM

**Comment by jbuchermn** [comment]
Are you using v0.3? (E.g. the AUR package)

Can you post your config? Maybe I'm missing something there.

And one more question.. does this happen when just using alacritty or are there other apps involved?

**Comment by MTRNord** [comment]
Hi I have the same issue with newm v0.3 Using the pip install (well technically gentoo but it is like doing it via pip).

I am using the default newm config for this.

**Comment by Rosc0e** [comment]
I Have the same issue, started from tty with gdm enabled and disabled,  after 1 to 2 min of idle it will shutdown, without me touching it after startup

**Comment by jbuchermn** [comment]
> Hi I have the same issue with newm v0.3 Using the pip install (well technically gentoo but it is like doing it via pip).
> 
> I am using the default newm config for this.

Did you notice any particular behaviour triggering the segfaults. I's very hard for me to debug this without being able to reproduce...



> I Have the same issue, started from tty with gdm enabled and disabled, after 1 to 2 min of idle it will shutdown, without me touching it after startup

That's probably unrelated, unless there is actually a segfault, i.e. crash. Shutting down on idle is configurable behaviour of newm - take a look there.

**Comment by MTRNord** [comment]
> > Hi I have the same issue with newm v0.3 Using the pip install (well technically gentoo but it is like doing it via pip).
> > 
> > I am using the default newm config for this.
> 
> Did you notice any particular behaviour triggering the segfaults. I's very hard for me to debug this without being able to reproduce...

Sadly not really. With debug on there was no error standing out to me before the segfault. It looks fairly similar to the log that was already shared. It doesn't make any difference if I open up a program or just dont do anything with the wm. Both times it segfaults after a few minutes. The stack trace suggests it is an animation but that's pretty much all I am aware of. I start it with the suggested sh files from newm and greeterd/tuigreet.

**Comment by jbuchermn** [comment]
That's quite interesting, I thought it's some particular app quitting that's causing the segfault. Logs suggest that it's in the corresponding wl-callback. 

Does the segfault appear even if you don't do anything after starting newm? Can you share a log in this scenario?

**Comment by jbuchermn** [comment]
Closing as should be fixed by https://github.com/jbuchermn/pywm/commit/7980012191e953440eca87e168c81d8185344c39
