### ISSUE TITLE
Pip is not able to install

### ISSUE THREAD

**Issue by Mesum-Hussain** [jbuchermn/pywm#11]
I was trying to install NEWM on Pop OS (21.10) via Pip and it failed to install Pywm as a dependency.

This is the output of the terminal:
`Collecting git+https://github.com/jbuchermn/pywm
  Cloning https://github.com/jbuchermn/pywm to /tmp/pip-req-build-mr5b_g0w
  Running command git clone -q https://github.com/jbuchermn/pywm /tmp/pip-req-build-mr5b_g0w
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-mr5b_g0w/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-mr5b_g0w/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-epasqyxo
         cwd: /tmp/pip-req-build-mr5b_g0w/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-mr5b_g0w/setup.py", line 6, in <module>
        proc = subprocess.Popen(["meson", "build"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'meson'
    ----------------------------------------
WARNING: Discarding git+https://github.com/jbuchermn/pywm. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by jbuchermn** [comment]
This complains about not having meson available. Be sure to install pywms dependencies (see README) first then it shouldn't be an issue
