### ISSUE TITLE
Error: Dependency "wayland-server" not found

### ISSUE THREAD

**Issue by Abcd2591** [jbuchermn/pywm#19]
I am on Nobara 36(Fedora based distro)
I get `meson.build:33:0: ERROR: Dependency "wayland-server" not found, tried pkgconfig and cmake` when running `pip3 install --user git+https://github.com/jbuchermn/pywm` even when libwayland-server is installed

**Comment by Abcd2591** [comment]
Seeing what you said on #12 I installed sway and I still get the error

**Comment by cben** [comment]
On my fedora i believe i got it from `libwayland-server` + `wayland-devel` packages (the later for header files)

**Comment by Abcd2591** [comment]
Installing `wayland-devel` worked. Thanks!
