### ISSUE TITLE
Is the proc_blur branch usable?

### ISSUE THREAD

**Issue by CRAG666** [jbuchermn/pywm#4]
Hi, I usually keep up with updates to newm and pywm, I currently use version 3 of both. A few days ago I saw this branch and I was wondering what its characteristics were and if it is possible to use newm v3 and pywm proc_blur? Thanks in advance and excellent work you do

**Comment by jbuchermn** [comment]
Hi,

thanks for continuing to test the most recent versions :)

poc_blur is almost ready, it's not yet integrated into newm, so there is no advantage to using that branch right now, plus there are bugs I'm working on atm.

Once this is integrated into newm, I'll comment on the issue https://github.com/jbuchermn/newm/issues/56

**Comment by CRAG666** [comment]
Great, I'll wait for the merger. I'll close these. Greetings
